library(maptools)
library(spdep)
oral<-readShapePoly("C:/Users/Janani Selvaraj/Documents/New folder (4)/data/prashanthi/boundarymergedd.shp")
pm<-probmap(oral$observed,oral$expected)
rt<-sum(oral$observed)/sum(oral$expected) 
ppois_pmap<-numeric(length(oral$expected)) 
for (i in seq(along=ppois_pmap)) 	
    {ppois_pmap[i]<-poisson.test(oral$observed[i],r=rt,T=(oral$expected[i]), alternative="less")$p.value } 
all.equal(ppois_pmap, pm$pmap) 
brks<-c(-Inf,2,2.5,3,3.5,Inf) 
cols<-grey(6:2/7) 
plot(oral,col=cols[findInterval(pm$raw*100000,brks,all.inside=TRUE)])
legend("bottomleft", fill=cols, legend=leglabs(brks), bty="n") 
title(main="Raw estimates of cancer incidences per 100000 per year") 
brks<-c(-Inf,47,83,118,154,190,Inf) 
cols<-cm.colors(6) 
plot(oral,col=cols[findInterval(pm$relRisk,brks,all.inside=TRUE)]) 
legend("bottomleft", fill=cols, legend=leglabs(brks), bty="n") 
title(main="Standardised incident ratios for Coimbatore cancer incidences") 
brks<-c(0,0.05,0.1,0.2,0.8,0.9,0.95,1) 
cols<-cm.colors(7) 
plot(oral,col=cols[findInterval(pm$pmap,brks, all.inside=TRUE)]) 
legend("bottomleft",fill=cols,legend=leglabs(brks),bty="n") 
title(main="Poisson probabilities for Coimbatore cancer incidences")
pm
