library(maptools)
library(RColorBrewer)
cbe_shp<-readShapePoly("C:/Users/Janani Selvaraj/Desktop/CBE_DF_POLYGON/CBE_DF_POLYGON.shp")
plot(cbe_shp)
summary(cbe_shp)
my.palette <- brewer.pal(n = 7, name = "Spectral")
my.palette <- brewer.pal(n = 7, name = "OrRd")
spplot(cbe_shp, "X014",  col.regions = my.palette, cuts = 6,col = "transparent")
library(classInt)
breaks.qt <- classIntervals(cbe_shp$X012, n = 6, style = "quantile", intervalClosure = "right")
spplot(cbe_shp, "X012", col = "transparent", col.regions = my.palette, 
       at = breaks.qt$brks)
library(SpatialEpiApp)
run_app()
